Improve web executor documentation to detail
ovh/venom pull request #292
Opened 2020-10-29 21:40 UTC by kevinramage

Improve web executor documentation to detail how integrate chrome features like headless mode and disable flags

Signed-off-by: Kevin RAMAGE <kevinramage@hotmail.fr>

2020-10-30 09:57 UTC, fsamin approved these changes

2020-10-31 13:52 UTC, ThomasCaud approved these changes

2020-11-09 15:09 UTC, yesnault requested changes

2020-11-09 15:09 UTC, yesnault commented on executors/web/README.md
> +History actions allow you to manipulate browser history actions. The following action are available:
```suggestion
History actions allow you to manipulate browser history actions. The following actions are available:
```

2020-11-09 15:09 UTC, yesnault commented on executors/web/README.md
> +This section describe some features specifics to chrome browser
```suggestion
This section describes some features specific to the Chrome browser
```

2020-11-09 15:09 UTC, yesnault commented on executors/web/README.md
> +To include chrome driver tests in your integration pipeline your must execute chrome in headless mode.
```suggestion
If you want to include Chrome Driver tests in your integration pipeline, you must execute Chrome in headless mode.
```

2020-11-09 15:09 UTC, yesnault commented on executors/web/README.md
> +To disable a feature, add an argument instance disable-features
```suggestion
In Chrome, you can turn experimental features on or off to test the behavior of upcoming features.
You can do this manually with chrome: // flags url with Chrome browser.
In Venom, to enable a feature, add an instance of the enable-features argument.
To disable a feature, add a disable-features argument instance
```

2020-11-09 15:12 UTC, merged