refactor: clean and simplify venom codebase
ovh/venom pull request #298
Opened 2020-11-13 16:38 UTC by fsamin

Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

2020-11-13 16:46 UTC, ovh-cds commented
CDS Report build-venom#270.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-13 17:05 UTC, yesnault requested changes

2020-11-13 17:05 UTC, yesnault commented on cli/venom/run/cmd.go
> +	//withEnv         bool
to delete

2020-11-13 17:05 UTC, yesnault commented on cli/venom/run/cmd.go
>  	Cmd.Flags().StringSliceVarP(&varFiles, "var-from-file", "", []string{""}, "--var-from-file filename.yaml --var-from-file filename2.yaml: hcl|json|yaml, must contains map[string]string'")
```suggestion
	Cmd.Flags().StringSliceVarP(&varFiles, "var-from-file", "", []string{""}, "--var-from-file filename.yaml --var-from-file filename2.yml: json|yml, must contains map[string]string'")
```

2020-11-13 17:10 UTC, yesnault requested changes

2020-11-13 17:10 UTC, yesnault commented on cli/venom/run/cmd.go
> +	//withEnv         bool
```suggestion
```

2020-11-13 17:10 UTC, yesnault commented on cli/venom/run/cmd.go
> +				return fmt.Errorf("unable to open var-file %s: %v", f, err)
```suggestion
				return fmt.Errorf("unable to open var-from-file %s: %v", f, err)
```

2020-11-14 20:32 UTC, ovh-cds commented
CDS Report build-venom#272.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-16 09:37 UTC, yesnault requested changes

2020-11-16 13:24 UTC, ovh-cds commented
CDS Report build-venom#273.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-16 14:07 UTC, ovh-cds commented
CDS Report build-venom#275.0 ✘  
* Build
  * Build ✘

2020-11-16 14:08 UTC, yesnault approved these changes

2020-11-16 15:12 UTC, ovh-cds commented
CDS Report build-venom#276.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-16 19:12 UTC, yesnault approved these changes

2020-11-16 19:19 UTC, ovh-cds commented
CDS Report build-venom#277.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-16 19:22 UTC, ovh-cds commented
CDS Report build-venom#278.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘  
  * Lib Unit Tests ✔

2020-11-16 20:22 UTC, merged