initial implementation of mqtt executor
ovh/venom pull request #401
Opened 2021-05-13 19:27 UTC by SimonT90poe

Add new executor to support MQTT message brokers

Signed-off-by: Simon Truss <Simon.Truss@90poe.io>

2021-06-07 14:33 UTC, ovh-cds commented
CDS Report build-venom-a#597.0 ■   
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ■

2021-06-07 14:33 UTC, ovh-cds commented
CDS Report build-venom-a#597.0 ■   
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ■

2021-06-07 15:11 UTC, ovh-cds commented
CDS Report build-venom-a#606.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-07 15:39 UTC, ovh-cds commented
CDS Report build-venom-a#609.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-08 08:54 UTC, yesnault commented
@SimonT90poe  thank you for this new executor.

Tests are failing, output:

```
 • MQTT testsuite (./mqtt.yml)
 	• MQTT-publish-testcase SUCCESS
	  [trac] writing MQTT-testsuite.MQTT-publish-testcase.step.0.dump.json
 	• MQTT-subscribe-testcase FAILURE
	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.0.dump.json
	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.1.dump.json
	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.2.dump.json
Testcase "MQTT subscribe testcase", step #2: Assertion "result.messages.__len__ ShouldEqual 1" failed. expected: 1  got: 0 (./mqtt.yml:49)
Testcase "MQTT subscribe testcase", step #2: Assertion "result.messagesjson.__len__ ShouldEqual 1" failed. expected: 1  got: 0 (./mqtt.yml:50)
Testcase "MQTT subscribe testcase", step #2: Assertion "result.messagesjson.messagesjson0.c ShouldEqual 1" failed. expected: 1  got: <nil> (./mqtt.yml:51)
Testcase "MQTT subscribe testcase", step #2: Assertion "result.topics.topics0 ShouldEqual \"venom/mqtt_test/topic\"" failed. expected: venom/mqtt_test/topic  got: <nil> (./mqtt.yml:0)
```
Can you take a look at this please ?

2021-06-08 08:57 UTC, yesnault requested changes

2021-06-08 08:57 UTC, yesnault commented on executors/mqtt/mqtt.go
> +	Topics []string `json:"topic" yaml:"topic"`
shouldn't be topics in annotation?

2021-06-08 09:12 UTC, SimonT90poe commented on executors/mqtt/mqtt.go
> +	Topics []string `json:"topic" yaml:"topic"`
yes, good catch.

2021-06-13 19:21 UTC, SimonT90poe commented
> @SimonT90poe thank you for this new executor.
> 
> Tests are failing, output:
[...]
> 
> Can you take a look at this please ?

The v2 docker container had changed the default behaviour and removed the unsecured listener. Added a config file to support MQTT over TCP.

resolved in 3488d70

2021-06-13 19:22 UTC, SimonT90poe commented on executors/mqtt/mqtt.go
> +	Topics []string `json:"topic" yaml:"topic"`
resolved in 9e989b9

2021-06-22 07:45 UTC, ovh-cds commented
CDS Report build-venom-a#628.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 08:18 UTC, ovh-cds commented
CDS Report build-venom-a#629.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 08:47 UTC, ovh-cds commented
CDS Report build-venom-a#630.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 08:52 UTC, SimonT90poe commented
Where do I find the build logs, because this was working on my own machine. The only possible issue I can think of is the dependency of the docker container I added.

2021-06-22 08:59 UTC, ovh-cds commented
CDS Report build-venom-a#631.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 13:26 UTC, ovh-cds commented
CDS Report build-venom-a#632.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 13:47 UTC, ovh-cds commented
CDS Report build-venom-a#633.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 14:12 UTC, ovh-cds commented
CDS Report build-venom-a#634.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 14:32 UTC, ovh-cds commented
CDS Report build-venom-a#635.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-06-22 21:28 UTC, yesnault commented
@SimonT90poe  Sorry for notification on this PR. It's ok now:

```
[INFO]  • MQTT testsuite (./mqtt.yml)
[INFO]  	• MQTT-publish-testcase SUCCESS
[INFO] 	  [trac] writing MQTT-testsuite.MQTT-publish-testcase.step.0.dump.json
[INFO]  	• MQTT-subscribe-testcase SUCCESS
[INFO] 	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.0.dump.json
[INFO] 	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.1.dump.json
[INFO] 	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.2.dump.json
[INFO] 	  [trac] writing MQTT-testsuite.MQTT-subscribe-testcase.step.3.dump.json
```

2021-06-22 21:29 UTC, yesnault approved these changes

2021-06-23 12:40 UTC, fsamin approved these changes

2021-06-23 12:44 UTC, sguiheux approved these changes

2021-06-23 12:44 UTC, merged