doc: testsuite sort on venom run
ovh/venom pull request #474
Opened 2021-12-21 13:51 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2021-12-21 14:10 UTC, ovh-cds commented
CDS Report build-venom-a#722.0 ✘  
* Build
  * Build ✔ 
* Tests
  * Acceptance Tests ✘

2021-12-21 14:26 UTC, marcaudefroy approved these changes

2021-12-27 09:22 UTC, fsamin requested changes

2021-12-27 09:22 UTC, fsamin commented on README.md
> +Venom does not sort testsuite files on run.
it's a bit "out of the blue"

2022-01-24 08:32 UTC, fsamin approved these changes

2022-01-24 08:32 UTC, merged