feat: add default value for var
ovh/venom pull request #549
Opened 2022-05-10 16:48 UTC by guoweis-outreach

today, if one of the json element can't be found, none of the resolution works

```yaml
name: Exec testsuite
testcases:
  - name: catjson
    steps:
      - script: cat exec/testa.json
        info: "the value of result.systemoutjson is {{.result.systemoutjson}}"
        assertions:
          - result.systemoutjson.foo ShouldContainSubstring bar
        vars:
          foo:
            from: result.systemoutjson.foo
          bar:
            from: result.systemoutjson.bar
            default: "test"
      - script: echo "{{.catjson.foo}}"
        info: "the value of foo is {{.catjson.foo}} {{.catjson.bar}}"
```
this is the output
```sh
 • Exec testsuite (tests/exec.yml)
 	• catjson FAILURE
	  [info] the value of result.systemoutjson is {"foo":"bar"} (tests/exec.yml:29)
	  [info] the value of foo is {{.catjson.foo}} {{.catjson.bar}} (tests/exec.yml:39)
```

This change allows a `default` value to be specified such that if it's missing from the json, the default value will be used.

2022-05-11 07:35 UTC, yesnault requested changes
Hi @guoweis-outreach,
Thank you for this proposal. It's ok to include that into venom. Can you:
- add some tests into tests/ directory
- add some doc about this into the README

Thank you

2022-05-13 02:50 UTC, guoweis-outreach commented
@yesnault does this seem good to you?

2022-05-13 09:56 UTC, yesnault approved these changes
Thank you @guoweis-outreach !

LGTM

2022-05-20 00:31 UTC, guoweis-outreach commented
@yesnault , before you merge, I'd like to make one more change to support this case. Do you know how I might achieve this? I need to look up the vars if the `default`'s value is a string, something like that?

```yaml
name: Exec testsuite
testcases:
  - name: catjson
    steps:
      - script: cat exec/testa.json
        info: "the value of result.systemoutjson is {{.result.systemoutjson}}"
        assertions:
          - result.systemoutjson.foo ShouldContainSubstring bar
        vars:
          foo:
            from: result.systemoutjson.foo
          bar:
            from: result.systemoutjson.bar
            default: "{{.somevar}}"
      - script: echo "{{.catjson.foo}}"
        info: "the value of foo is {{.catjson.foo}} {{.catjson.bar}}"

```

2022-06-15 15:06 UTC, merged