add mongo executor
ovh/venom pull request #601
Opened 2022-11-08 16:17 UTC by Thiht

Test result:

```
➜  venom git:(master) go run cmd/venom/main.go run tests/mongo.yml
	  [trac] writing venom.44.log
 • MongoDB Test Suite (tests/mongo.yml)
 	• Reset-collection PASS
 	• Insert-some-data PASS
	  [info] [{"InsertedIDs":["636a7c57d044a5a54b0f8cf7","636a80d7cba602a7ce757d9a"]},{"InsertedIDs":["636a80d7cba602a7ce757d9b","636a80d7cba602a7ce757d9c","636a80d7cba602a7ce757d9d","636a80d7cba602a7ce757d9e","636a80d7cba602a7ce757d9f","636a80d7cba602a7ce757da0","636a80d7cba602a7ce757da1","636a80d7cba602a7ce757da2","636a80d7cba602a7ce757da3","636a80d7cba602a7ce757da4","636a80d7cba602a7ce757da5","636a80d7cba602a7ce757da6"]}]
 	• Count-the-inserted-data PASS
	  [info] [{"count":14},{"count":3}]
 	• Search-the-inserted-data PASS
	  [info] [{"results":[{"_id":"636a7c57d044a5a54b0f8cf7","color":"black","value":"joker"},{"_id":"636a80d7cba602a7ce757d9a","color":"red","value":"joker"},{"_id":"636a80d7cba602a7ce757d9b","suit":"clubs","value":"jack"},{"_id":"636a80d7cba602a7ce757d9c","suit":"clubs","value":"queen"},{"_id":"636a80d7cba602a7ce757d9d","suit":"clubs","value":"king"},{"_id":"636a80d7cba602a7ce757d9e","suit":"diamonds","value":"jack"},{"_id":"636a80d7cba602a7ce757d9f","suit":"diamonds","value":"queen"},{"_id":"636a80d7cba602a7ce757da0","suit":"diamonds","value":"king"},{"_id":"636a80d7cba602a7ce757da1","suit":"hearts","value":"jack"},{"_id":"636a80d7cba602a7ce757da2","suit":"hearts","value":"queen"},{"_id":"636a80d7cba602a7ce757da3","suit":"hearts","value":"king"},{"_id":"636a80d7cba602a7ce757da4","suit":"spades","value":"jack"},{"_id":"636a80d7cba602a7ce757da5","suit":"spades","value":"queen"},{"_id":"636a80d7cba602a7ce757da6","suit":"spades","value":"king"}]},{"results":[{"_id":"636a7c57d044a5a54b0f8cf7","color":"black","value":"joker"}]},{"results":[{"_id":"636a7c57d044a5a54b0f8cf7","color":"black","value":"joker"}]}]
 	• Update-the-data PASS
	  [info] [{"MatchedCount":3,"ModifiedCount":3,"UpsertedCount":0,"UpsertedID":null},{"count":4}]
 	• Delete-some-data PASS
	  [info] [{"DeletedCount":3},{"count":0},{"count":11}]
 	• Aggregate-pipeline PASS
	  [info] [{"results":[{"_id":"queen","count":3},{"_id":"jack","count":3},{"_id":"king","count":3}]}]
final status: PASS
```

2022-11-09 09:56 UTC, yesnault commented
Thank you @Thiht !
We'll plan to merge it in venom 1.2. (after adding mongo in our integration tests)

2022-11-09 10:22 UTC, fsamin requested changes
thanks a lot, this is dope !
just a little feedback on your assertions.

i think we will merge this just after the release of 1.1.0, this feature will be released in the next 1.2.0-beta

2022-11-09 10:22 UTC, fsamin commented on tests/mongo.yml
> +          - result.actions.actions0.insertedids.__len__ ShouldEqual 2
could you use assertion `ShouldHaveLength` instead of `__len__`, we will try to deprecate those old ugly properties in a near future

2022-12-06 08:16 UTC, yesnault requested changes
Thank you @Thiht 

can you update the tests/Makefile to trigger integration test with mongo please (`venom-mongo.cid` target)?

2022-12-06 09:36 UTC, Thiht commented
Done!

2023-02-13 15:55 UTC, yesnault approved these changes

2023-02-13 15:56 UTC, merged