Add support for sqlite3 to dbfixtures executor
ovh/venom pull request #613
Opened 2022-12-27 08:57 UTC by etandel

It seems the underlying libraries used by `dbfixtures` support sqlite3, so I'm adding support for it as well.

I **think** the tests are passing locally, that's why I'm opening this PR, but TBH I'm not completely sure: `make integration-test` exits successfully with `0`, but I don't see any venom output in my stdout.

Do let me know if anything else needs changing.

2022-12-27 10:49 UTC, ovh-cds commented
CDS Report build-venom-a#1061.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2022-12-27 10:54 UTC, fsamin requested changes

2022-12-27 10:54 UTC, fsamin commented on tests/db_fixtures.yml
> +- name: initialize-postgresql-database-with-migrations
```suggestion
- name: initialize-sqlite3-database-with-migrations
```

2022-12-27 10:54 UTC, fsamin commented
Hello,
thank you for your contribution, to run the tests please try the following:

# unit tests:
 - make test

 # integration tests:
- make build OS=linux ARCH=amd64
- cp dist/venom.linux-amd64 tests/venom
- cd tests
- make start-test-stack (wait a few seconds)
- make build-test-binary-docker
- make run-test

you can also give a try to gitpod https://www.gitpod.io/ https://github.com/ovh/venom/blob/master/.gitpod.yml

i run the tests in our CI and it is failing `failed to ping database: invalid uri authority` on test initialize-postgresql-database-with-migrations (see suggestion)

2022-12-27 16:05 UTC, etandel commented
Hi @fsamin, thanks a lot for the review and the additional instructions on running the integration tests.

I just pushed some fixes and `dbfixture` tests are passing locally. There are a few unrelated integration tests that are failing (e.g. SSH), probably due to my local setup.

I also took the liberty of adding your testing instructions to the main README under the `Hacking` section.

2022-12-29 14:32 UTC, fsamin requested changes

2022-12-29 14:32 UTC, fsamin commented on executors/dbfixtures/README.md
> +  - database mandatory [mysql/postgres/sqlit3]
```suggestion
  - database mandatory [mysql/postgres/sqlite3]
```

2023-01-03 08:31 UTC, fsamin approved these changes

2023-01-03 08:31 UTC, fsamin commented
LGTM

2023-01-04 10:45 UTC, yesnault approved these changes

2023-01-04 10:45 UTC, yesnault commented
LGTM, thank you @etandel

2023-01-04 10:46 UTC, merged

2023-01-04 12:30 UTC, etandel commented
Thanks everyone!