feat: allow specifying query parameters
ovh/venom pull request #629
Opened 2023-02-10 05:16 UTC by guoweis-outreach

This allows specifying the query parameters and properly encode them.

2023-02-14 11:06 UTC, yesnault requested changes
Hi @guoweis-outreach , thank you for this PR.

Can you add documentation on http/README.md file, and  unit test and/or tests into tests/ directory about that please?

Thank you

2023-02-15 09:41 UTC, ovh-cds commented
CDS Report build-venom-a#1086.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-02-16 04:53 UTC, guoweis-outreach commented
@yesnault i'm not sure how to run `Acceptance Tests` or where to find the log why `Acceptance Tests` failed. Any tips?

2023-05-03 06:12 UTC, yesnault approved these changes

2023-05-03 06:58 UTC, ovh-cds commented
CDS Report build-venom-a#33.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-05-03 13:13 UTC, ovh-cds commented
CDS Report build-venom-a#37.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-05-04 08:32 UTC, yesnault requested changes

2023-05-04 08:32 UTC, yesnault commented on tests/http.yml
> +      - result.bodyjson.args.b ShouldEqual " b"
```suggestion
      - result.bodyjson.args.a ShouldEqual " b"
```

2023-05-04 08:53 UTC, ovh-cds commented
CDS Report build-venom-a#43.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-05-04 09:18 UTC, merged