(executor/kafka) Added an option to allow self-signed certs
ovh/venom pull request #648
Opened 2023-03-16 13:51 UTC by Armadindon

2023-05-02 19:45 UTC, yesnault requested changes

2023-05-02 19:45 UTC, yesnault commented on executors/kafka/kafka.go
> +		InsecureTLS bool `json:"insecure_tls,omitempty" yaml:"InsecureTLS,omitempty"`
```suggestion
		InsecureTLS bool `json:"insecure_tls,omitempty" yaml:"insecure_tls,omitempty"`
```

2023-05-02 19:45 UTC, yesnault approved these changes

2023-05-02 19:53 UTC, ovh-cds commented
CDS Report build-venom-a#1116.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-05-03 06:14 UTC, yesnault commented
@Armadindon Thank you!

2023-05-03 06:15 UTC, merged