Update the skip as it was not working correctly
ovh/venom pull request #685
Opened 2023-06-19 16:45 UTC by fokion

It could not evaluate a variable that was defined on previous steps and during processing.

In the venom.log we would see something like that in the comparison
```
[skip-something] evaluating out ShouldEqual '1'
[skip-something] failed to evaluate : expected: 1  got: <nil>
```
which means that it does not get the value of `out` 

now it is  only `[skip-something] evaluating out ShouldEqual '1'` which means that it  evaluates  it correctly.

furthermore the test is working correctly 

```
 • Testing skip (skip/skip.yml)
        • skip-something
                •  PASS
                  [info] Set a variable to 1
                • exec PASS
                •  PASS
                  [info] do not skip it as the value of out is different to 2
                • skip-this SKIP
                • exec PASS
                •  SKIP
                •  SKIP
```

for 

```
name : "Testing skip"
testcases:
  - name : "skip something"
    steps:
      - info:
          - Set a variable to 1
      - script : "echo '1'"
        vars :
          out:
            from : result.systemout
      - info:
          - "do not skip it as the value of out is different to 2"
        skip :
          - out ShouldEqual '2'
      - name: skip-this
        skip:
          - out ShouldEqual '1'
      - script: "echo 'false'"
        vars:
          outAsBool:
            from: result.systemout
      - info:
          - "Fail should be skipped"
        skip :
          - out ShouldEqual 1
      - info:
          - "Fail should be skipped as false"
        skip:
          - outAsBool ShouldBeFalse
```

2023-06-19 17:01 UTC, fokion commented
@yesnault  , @fsamin  any thoughts?

2023-06-19 19:52 UTC, fokion commented
#651

2023-06-23 14:31 UTC, ovh-cds commented
CDS Report build-venom-a#64.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-07-19 12:10 UTC, ovh-cds commented
CDS Report build-venom-a#70.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-07-25 09:06 UTC, yesnault requested changes
the current output is:

```
❯ go run main.go run -v skip.yml
          [trac] writing venom.3.log
 • Testing skip (skip.yml)
        • skip-something
                •  PASS
                  [info] Set a variable to 1 (skip.yml:11)
                • exec PASS
                •  SKIP
                • skip-this PASS
                • exec PASS
                •  PASS
                  [info] Fail should be skipped
                •  PASS
                  [info] Fail should be skipped as false
```

I'm not sure to understand why it's no different with your output.

2023-07-25 11:31 UTC, fokion commented
> the current output (with your code) is:
> 
> ```
> ❯ go run main.go run -v skip.yml
>           [trac] writing venom.3.log
>  • Testing skip (skip.yml)
>         • skip-something
>                 •  PASS
>                   [info] Set a variable to 1 (skip.yml:11)
>                 • exec PASS
>                 •  SKIP
>                 • skip-this PASS
>                 • exec PASS
>                 •  PASS
>                   [info] Fail should be skipped
>                 •  PASS
>                   [info] Fail should be skipped as false
> ```
> 
> I'm not sure to understand why it's so different with your output.

missed some commits from a rebase see commit [0d1dfe3](https://github.com/ovh/venom/pull/685/commits/0d1dfe35c8d374688fa73c63442e5643b2bb1ea8)

```
          [trac] writing venom.3.log
 • Skip testsuite (/Users/fokionsotiropoulos/GolandProjects/venom/tests/skip.yml)
        • init
                • exec PASS
        • do-not-skip-this
                • exec PASS
        • skip-this
                • (all steps were skipped)
        • skip-one-of-these
                • do-not-skip-this PASS
                • skip-this SKIP
        • skip-all-of-steps
                • skip-this SKIP
final status: PASS
```

2023-07-25 15:50 UTC, ovh-cds commented
CDS Report build-venom-a#75.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-07-27 16:02 UTC, fokion commented
> 

can you checkout to that branch instead of pulling to your own branch and run the test?

go run main.go run -v ../../tests/skip/skip.yml

2023-07-27 16:38 UTC, fokion commented
@yesnault  found it... I am running **go run main.go run -v ../../tests/skip.yml** not tests/skip/skip.yml . The skip/skip.yml actually is a wrong test as the `outAsBool` is false and those 2 info statements must be visible
```
      - script: "echo 'false'"
        vars:
          outAsBool:
            from: result.systemout
      - info:
          - "Fail should be skipped"
        skip :
          - out ShouldEqual 1
      - info:
          - "Fail should be skipped as false"
        skip:
          - outAsBool ShouldBeFalse
```

2023-07-28 08:05 UTC, ovh-cds commented
CDS Report build-venom-a#76.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-07-28 09:05 UTC, yesnault commented
@fokion 

```
❯ go run main.go run -v ../../tests/skip.yml
          [trac] writing venom.30.log
 • Skip testsuite (../../tests/skip.yml)
        • init
                • exec PASS
        • do-not-skip-this
                • (all steps were skipped)
        • skip-this
                • exec FAIL
                  Testcase "skip-this", step #0-0: Assertion "result.code ShouldEqual 0" failed. expected: 0  got: 127 (skip.yml:0)
        • skip-one-of-these
                • do-not-skip-this PASS
                • skip-this SKIP
        • skip-all-of-steps
                • skip-this SKIP

2023-08-04 09:19 UTC, fokion commented
@yesnault  I have updated the code in here as it was due to the variables not being passed for the assertion https://github.com/ovh/venom/pull/708

2023-08-04 09:19 UTC, closed without merging