Feature/xmlreport test id
ovh/venom pull request #688
Opened 2023-06-22 00:12 UTC by ivan-velasco

- For reporting back to a test case matrix, each test case should contain a test case id
Plan to use the generated .xml and parse the id's to update test case management solution after each CI run

```yml
name: TestSuite 

testcases:
  - name: without_id
    steps:
    - type: user_executor
      vars:
        foo:
          from: result.foo

  - name: with_test_id
    id: C1999
    steps:
    - type: user_executor
      foo: "{{.without_id.foo}}"

```
Report output:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite name="TestSuite" package="test.yml" tests="2" time="20">
    <testcase classname="test.yml" name="without_id" time="0.1">
      <system-out><![CDATA[
]]></system-out>
      <system-err><![CDATA[
]]></system-err>
    </testcase>
    <testcase classname="test.yml" name="with_test_id" time="22" id="C1999">
      <system-out><![CDATA[

]]></system-out>
      <system-err><![CDATA[

]]></system-err>
    </testcase>
  </testsuite>
</testsuites>
```

2023-07-25 09:29 UTC, ovh-cds commented
CDS Report build-venom-a#74.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-07-28 09:08 UTC, yesnault requested changes

2023-07-28 09:08 UTC, yesnault commented on types.go
> +	Id        string       `xml:"id,attr,omitempty" json:"id" yaml:"id"`
```suggestion
	ID        string       `xml:"id,attr,omitempty" json:"id" yaml:"id"`
```

2023-07-28 09:08 UTC, yesnault commented on types.go
> +	Id           string            `json:"id" yaml:"id"`
```suggestion
	ID           string            `json:"id" yaml:"id"`
```

2023-07-28 09:08 UTC, yesnault commented on venom_output.go
> +				Id:        tc.Id,
```suggestion
				ID:        tc.ID,
```

2023-07-28 09:36 UTC, yesnault approved these changes

2023-07-28 09:38 UTC, merged