parse yaml files in the readfile
ovh/venom pull request #689
Opened 2023-06-24 08:52 UTC by fokion

Have the ability to parse yaml files as well and give the contentjson

2023-06-26 07:20 UTC, ovh-cds commented
CDS Report build-venom-a#65.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-06-26 08:10 UTC, ovh-cds commented
CDS Report build-venom-a#65.1 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✘

2023-06-27 12:07 UTC, yesnault requested changes

2023-06-27 12:07 UTC, yesnault commented on executors/readfile/README.md
> +        filetype: yaml
filetype: no need to add a new attribute filetype. If yml or yaml, we should extract the values, as it's already done with json format.

2023-07-28 09:28 UTC, yesnault requested changes

2023-07-28 09:28 UTC, yesnault commented on executors/readfile/README.md
> +        filetype: yaml
```suggestion
```

2023-09-06 14:44 UTC, yesnault approved these changes

2023-09-06 15:05 UTC, ovh-cds commented
CDS Report build-venom-a#82.0 ✘  
* Build
  * Build ✔ 
  * Unit Tests ✔ 
* Tests
  * Acceptance Tests ✔ 
* Package-Analyze
  * Docker -   
  * Sonar ✘

2023-09-07 07:48 UTC, merged