http: feature/xml systemout
ovh/venom pull request #720
Opened 2023-09-20 18:50 UTC by ivan-velasco

http: addition of 'systemout' to the XML report for enhanced debugging capabilities, eliminating the need to solely rely on 'INFO' messages or enabling verbose mode after a complete run. With this enhancement, 'systemout' will be included in the XML output specifically when errors occur, improving the troubleshooting and diagnostic process.

2023-09-20 22:06 UTC, alexhaywardsocotra approved these changes

2023-09-21 07:20 UTC, yesnault approved these changes
Hi, thank you for this proposal. I'm not sure about the performance impact with big payload, but yes, this could be useful. LGTM.

2023-09-27 15:22 UTC, yesnault commented
After re-reading, I think that the body will be present twice in the JSON output. Maybe we can avoid that with the json annotation to '-'.

2023-09-27 15:22 UTC, yesnault requested changes

2023-09-27 15:23 UTC, yesnault commented on executors/http/http.go
> +	Systemout   string      `json:"systemout,omitempty" yaml:"systemout,omitempty"`
ok with that @ivan-velasco  ?

2023-10-05 18:17 UTC, ivan-velasco commented on executors/http/http.go
> +	Systemout   string      `json:"systemout,omitempty" yaml:"systemout,omitempty"`
Going to test this change out locally today @yesnault

2023-10-18 21:30 UTC, ivan-velasco commented on executors/http/http.go
> +	Systemout   string      `json:"systemout,omitempty" yaml:"systemout,omitempty"`
@yesnault tested this finally today and it causes the xml report to exclude this information
When the property is set `Systemout   string      json:"-" yaml:"-"`
```xml
<system-out><![CDATA[
```
json report
```json
"systemout": "\n",
```

When the property is set `Systemout   string      json:"systemout,omitempty" yaml:"systemout,omitempty"`, then xml report shows up properly
```xml
<system-out><![CDATA[
PATCH-----http://
```
json report
```json
"result.systemout": "PATCH-----http://
"systemout": "PATCH-----http://
```

2023-11-13 19:00 UTC, ivan-velasco commented on executors/http/http.go
> +	Systemout   string      `json:"systemout,omitempty" yaml:"systemout,omitempty"`
@yesnault Any thoughts on this? Has been very helpful in identifying errors quickly.

2023-11-29 10:15 UTC, yesnault approved these changes

2023-11-29 10:49 UTC, merged