fix env variables with equal sign
ovh/venom pull request #721
Opened 2023-09-23 02:11 UTC by bramca

This PR fixes the following issue:
VENOM_VAR_a='host=localhost'
results in a='host' because of the split on '=' and only taking the first value back

With this the var would end up like this:
a = 'host=localhost'

Making it possible to add equal signs in the variable

2023-09-27 15:15 UTC, yesnault requested changes
Hi @bramca , thank you for your proposal.

Can you add a unit test about that into https://github.com/ovh/venom/blob/master/cmd/venom/run/cmd_test.go#L92 please?

2023-09-28 07:48 UTC, bramca commented
Added a unit test for it

2023-09-28 09:04 UTC, yesnault requested changes
I think that SplitN is more readable than `strings.Join..[1:].., '='`

2023-09-28 09:04 UTC, yesnault commented on cmd/venom/run/cmd.go
>  			tuple := strings.Split(env, "=")
```suggestion
			tuple := strings.SplitN(a, "=", 2)
```

2023-09-28 09:04 UTC, yesnault commented on cmd/venom/run/cmd.go
> +			variables = append(variables, fmt.Sprintf("%v=%v", k, cast(strings.Join(tuple[1:], "="))))
```suggestion
			variables = append(variables, fmt.Sprintf("%v=%v", k, cast(tuple[1])))
```

2023-09-28 09:04 UTC, yesnault commented on cmd/venom/run/cmd.go
> +			variables = append(variables, fmt.Sprintf("%v=%v", k, cast(strings.Join(tuple[1:], "="))))
```
package main

import (
	"fmt"
	"strings"
)

func main() {
	a := "a=b=c"
	t := strings.SplitN(a, "=", 2)
	fmt.Printf("0 %v\n", t[0])
	fmt.Printf("1 %v\n", t[1])
}

```
return 

```
0 a
1 b=c

2023-09-28 10:04 UTC, bramca commented on cmd/venom/run/cmd.go
>  			tuple := strings.Split(env, "=")
agreed, good suggestion

2023-09-28 10:04 UTC, bramca commented on cmd/venom/run/cmd.go
> +			variables = append(variables, fmt.Sprintf("%v=%v", k, cast(strings.Join(tuple[1:], "="))))
Changed it to SplitN

2023-09-28 13:19 UTC, yesnault commented
LGTM, thank you

2023-09-28 13:22 UTC, fsamin approved these changes

2023-09-28 14:50 UTC, merged