add flag VENOM_LOGS_WITH_TIMESTAMP
ovh/venom pull request #722
Opened 2023-09-27 22:30 UTC by fokion

When we are emitting the logs of an executor with the flag `vv` we will be overwriting with the logs of that last execution for that executor. In order to have unique logs and capture every step we need to have the timestamp in the name of the json file.

2023-09-28 08:54 UTC, yesnault commented
Hi @fokion , thank you for this proposition.

For those who read this pull-request, the issue is about that:

```
❯ ./venom run -vv b.yml
          [trac] writing venom.log
 • Hide Secret (b.yml)
        • myvar_first
                • exec PASS
                  [trac] writing b.myvar_first.step.0.0.dump.json
        • myvar_first
                • exec PASS
                  [trac] writing b.myvar_first.step.0.0.dump.json
```

Here, we have two files, with the same filename

We don't want to add a new flag about that, and perhaps that we can have a filename containing the testcase number.
As these files are linked to the venom.x.log file too, perhaps that we can add the `x` number is the filename too (and explain the dump.json filename parts in the readme).

2023-09-28 08:55 UTC, yesnault requested changes
Hi @fokion , thank you for this proposition.

For those who read this pull-request, the issue is about that:

```
❯ ./venom run -vv b.yml
          [trac] writing venom.log
 • Hide Secret (b.yml)
        • myvar_first
                • exec PASS
                  [trac] writing b.myvar_first.step.0.0.dump.json
        • myvar_first
                • exec PASS
                  [trac] writing b.myvar_first.step.0.0.dump.json
```

Here, we have two files, with the same filename

We don't want to add a new flag about that, and perhaps that we can have a filename containing the testcase number.
As these files are linked to the venom.x.log file too, perhaps that we can add the `x` number is the filename too (and explain the dump.json filename parts in the readme).

2023-10-05 18:16 UTC, ivan-velasco commented
The testcase number is helpful, ideally the `testsuiteName_testcaseNumber` would make it easier to identify which log to view when errors occur.

2023-10-20 07:04 UTC, yesnault commented
see https://github.com/ovh/venom/pull/729

2023-10-20 07:04 UTC, closed without merging